name: Build and publish Iris Docker image

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Cache Latest Release Tag
      id: cache-tag
      uses: actions/cache@v2
      with:
        path: cache/tag
        key: latest-release-tag
        restore-keys: |
          latest-release-tag
          
    - name: Get Latest Release Tag
      if: steps.cache-tag.outputs.cache-hit != 'true'
      id: latest-tag
      run: |
        TAG_NAME=$(curl -s "https://api.github.com/repos/dfir-iris/iris-web/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "Latest tag: $TAG_NAME"
        if [ -n "$TAG_NAME" ]; then
          echo "$TAG_NAME" > cache/tag/latest-release-tag
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        else
          echo "No new release found."
          exit 1
        fi
      
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        repository: dfir-iris/iris-web
        ref: ${{ steps.latest-tag.outputs.tag_name }}
        path: iris-web

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: "./iris-web"
        file: iris-web/docker/webApp/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/dfir-iris-web:${{ steps.latest-tag.outputs.tag_name }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/dfir-iris-web:latest
