name: Build and publish Iris Docker image

on:
  release:
    types: [published]
    repos: dfir-iris/iris-web
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run shell commands
      run: |
        git config --global url.https://github.com/.insteadOf git://github.com/
        git clone --branch v2.0.0 https://github.com/dfir-iris/iris-web.git
        cd iris-web
        cp .env.model .env
        TAG=dfir-iris/iris-web:2.0.0 docker-compose build app

    - name: Publish Docker Image
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker push dfir-iris/iris-web:2.0.0
