name: Build and publish Iris Docker image

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Get Latest Release Tag
      id: latest-tag
      run: |
        TAG_NAME=$(curl -s "https://api.github.com/repos/dfir-iris/iris-web/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
      
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        repository: dfir-iris/iris-web
        ref: ${{ steps.latest-tag.outputs.tag_name }}
        path: iris-web
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}:iris-web"
        file: iris-web/docker/webApp/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
