name: Build and publish Iris Docker image

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        repository: dfir-iris/iris-web
        ref: $(git describe --abbrev=0 --tags)
        path: .

    - name: Build Docker Image
      run: |
        docker build -t jnimmo/dfir-iris:webapp-$(git describe --abbrev=0 --tags) . -f docker/webApp/Dockerfile

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Publish Docker Image
      run: |
        docker push jnimmo/dfir-iris:webapp-$(git describe --abbrev=0 --tags)
