name: Build and publish Iris Docker image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Run daily at midnight

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Get Latest Release Tag
      id: latest-tag
      uses: actions/github-script@v6
      with:
        script: |
          const { data } = await github.rest.repos.getLatestRelease({
            owner: 'dfir-iris',
            repo: 'iris-web'
          });
          console.log(`Latest Release Tag: ${data.tag_name}`);
          return data.tag_name.replace(/^"(.*)"$/, '$1')

    - name: Check if latest tag has already been built
      id: check-cache
      uses: actions/cache@v3
      with:
        path: cache/tag
        key: ${{ steps.latest-tag.outputs.result }}
      if: steps.latest-tag.outputs.result != ''
          
    - name: Exit if latest tag has already been built
      run: |
        if [ "${{ steps.check-cache.outputs.cache-hit }}" = "true" ]; then
          echo "Latest release has already been built. Skipping build."
          exit 0
        fi
      if: steps.check-cache.outputs.cache-hit == 'true'
      
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        repository: dfir-iris/iris-web
        ref: "${{ steps.latest-tag.outputs.result }}"
        path: iris-web

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: "./iris-web"
        file: iris-web/docker/webApp/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/dfir-iris-web:${{ steps.latest-tag.outputs.result }}
          ${{ secrets.DOCKER_HUB_USERNAME }}/dfir-iris-web:latest
          
    - name: Save tag to cache
      uses: actions/cache@v2
      with:
        path: cache/tag
        key: ${{ steps.latest-tag.outputs.result }}
        restore-keys: |
          cache/tag
