name: Build and publish Iris Docker image

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Get Latest Release Tag
      id: latest-tag
      run: |
        TAG_NAME=$(curl -s "https://api.github.com/repos/<github_username>/<repository_name>/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        repository: dfir-iris/iris-web
        ref: ${{ steps.latest-tag.outputs.tag_name }}
        path: .

    - name: Build Docker Image
      run: |
        docker build -t jnimmo/dfir-iris:webapp-$(git describe --abbrev=0 --tags) . -f docker/webApp/Dockerfile

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Publish Docker Image
      run: |
        docker push jnimmo/dfir-iris:webapp-${{ steps.latest-tag.outputs.tag_name }}
