name: Build and publish Iris Docker image

on:
  release:
    types: [published]
    repos: dfir-iris/iris-web
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        name: dfir-iris/iris-web
        ref: v2.0.0

    - name: Build Docker Image
      run: |
        cd iris-web
        cp .env.model .env
        docker build -t dfir-iris/iris-web:v2.0.0

    - name: Publish Docker Image
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker push dfir-iris/iris-web:v2.0.0
